### ISSUE TITLE
Prevent block editor to popup without any block selected

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#55]
When one clicks on an empty event or action block, the block editor is opened but no block is shown. Moreover, the ok button is active, which is incorrect because the state is wrong.

This should be corrected, the options are:
- select a block by default, such as the first one
- show an icon or animation inviting to drop a block

In any case, the ok button should be disabled

**Comment by stephanemagnenat** [comment]
After discussion with @mbonani and @cbarraud, we agreed that when clicking on an empty block spot, the first block of the list should be selected.

**Comment by Vincebecker** [comment]
I just had the same surprise !

I have two propositions :
1) Is this possible to put the list of blocks ( that is in the right) in the center of the screen, so it's clear that you have to make a choice ?

2) maybe when you click on an empty block the text could be "Select a block" instead of "edit a block" and it switches to "Edit a block" when you select it.

I have the feeling that if the first block of the list is selected by default it will look like a bug.

**Comment by stephanemagnenat** [comment]
Hi @Vincebecker these are both good ideas! The question is whether they are better than selecting the first block, as they both imply more work. I particularly like 2, and we could have an arrow showing the side of the screen where blocks are.

**Comment by Vincebecker** [comment]
I think It's a good compromise ! It will be clear that you have to do something.

**Comment by stephanemagnenat** [comment]
Implemented 2. in abd45c2.
