### ISSUE TITLE
Blocks should not have a violet layer

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-vpl2#61]
Because of visual compatibility with original test advanced mode, blocks in reactive mode have a violet layer around them, highlighting in yellow when they are executed. As the new FSM mode will have show different information (see #51), and the whole pair will be highlighted (see #38), this visual is now irrelevant.

**Comment by marvelous** [comment]
We still have the case where the block has a red ring, indicating an error (for example with #10).

**Comment by stephanemagnenat** [comment]
Can we do the same as in VPL1? For instance using a small arrow below the offending blocks? As far as I have observed and been told, VPL1 is very usable and easy to understand regarding these.

**Comment by marvelous** [comment]
Ok! I just discovered that the yellow highlight ring also appears when dragging a block over an other block. Should I remove that case as well?

**Comment by stephanemagnenat** [comment]
What is important is to have a visual feedback indicating potential drop. In VPL1, the dotted square become full to indicate that, and an existing block has some added elements on top and bottom to indicate potential drop. I think that a similar approach can be used. The exact visuals are not as important as their function. Of course, they should look clean and match the rest of the style. I suggest you have a look at VPL1 (you can use the simulator if you do not have a Thymio, or asebadummynode and launch thymiovpl with the `-anytarget` command line option).

**Comment by marvelous** [comment]
I looked at VPL1 and prefer the highlight we currently have in VPL2: it's the same yellow ring when dragging over a placeholder and when dragging over an existing block. So I'll leave the yellow ring.

As for errors, I prefer the red circle around the blocks that have an issue rather than the whole line being in red. I don't see the case where an error is for the whole line. It's always about some blocks. We can add the other error markers (exclamation point and connecting arrow) later.
