### ISSUE TITLE
Move files around

### ISSUE THREAD

**Issue by marvelous** [aseba-community/thymio-vpl2#96]
#35 https://github.com/aseba-community/thymio-vpl2/issues/35#issuecomment-293290663

**Comment by stephanemagnenat** [comment]
Great! I have two small questions:
- Should we also move the `.cpp/.h` files from the top-level to an `src/` subdirectory?
- The source translation files are in `translations/` in the top-level while the generated `.qm` files are within the `thymio-vpl2` sub-directory. As translations are generated through `thymio-vpl2.pri`, I am wondering whether the `.ts` files won't be better inside the `thymio-vpl2` sub-directory.

**Comment by marvelous** [comment]
- no, stop splitting by file type
- yes, I suppose

**Comment by stephanemagnenat** [comment]
Agreed not to split files by type, so these two questions are actually a single one: shouldn't all implementation files that are part of the `thymio-vpl2` library be in that sub-folder, rather than only the ones going into the resources? That would include the `.cpp/.h` files and the translation sources. Within the `thymio-vpl2` subfolder, we could add more structure if need, such as creating a widget directory for things like `FloatingActionButton.qml` or, for example, a directory for the editors.
